name: Generate Snake

on:
  # Runs everyday at 1:00
  schedule:
    - cron: "0 1 * * *" 
  
  # Allows to manually run the job at any time
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg?palette=github
      # Push the content to a "snake" branch
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
